# -*- coding: utf-8 -*-
"""EGC Script.ipynb

Automatically generated by Colaboratory.
Author: Matt Kokolus, mjkokolus@gmail.com
"""

import csv
import os
import ast

def findMissing(list1, list2):
  missingVals = []
  for element in list1:
      if element not in list2:
          missingVals.append(element)
 
  return missingVals

with open('OrganizationEventAttendancesEGC.csv', mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    line_count = 0
    studentList = []
    for row in csv_reader:
        if line_count == 0:
          print(f'Column names are {", ".join(row)}')
          line_count += 1
          studentList.append(f'{row["First Name"]} {row["Last Name"]}') #adds string value first last into studentList
        #print(f'\t{row["First Name"]} {row["Last Name"]} has {row["Attendance Status"]} the meeting.')
        line_count += 1
    #print(f'Processed {line_count} lines.')

#loadpreviousmasterstudentlist
save_file = 'masterStudentList.txt'
if os.path.exists(save_file):
  with open(save_file) as f:
    masterStudentList = ast.literal_eval(f.read())

for student in studentList:
  if student not in masterStudentList:
    masterStudentList.append(student) #checks if student has previously attended meetings and if not adds them to list
studentsNotAttended = findMissing(masterStudentList, studentList)

# save list in file
with open(save_file, 'w') as f:
  f.write(str(masterStudentList))

if not studentsNotAttended:
  print("Everyone attended!")
else:
  print(studentsNotAttended)
